spring.application.name=fitforge

# ===============================
# DATABASE CONFIGURATION
# ===============================

# MySQL database URL
spring.datasource.url=jdbc:postgresql://ep-billowing-brook-b5sg68dl-pooler.c-7.us-east-2.aws.neon.tech/fitforge?sslmode=require&channel_binding=require

#postgresql://neondb_owner:npg_0FvTX1UGYZPQ@ep-billowing-brook-b5sg68dl-pooler.c-7.us-east-2.aws.neon.tech/fitforge?sslmode=require&channel_binding=require

# MySQL username
spring.datasource.username=neondb_owner

# MySQL password
spring.datasource.password=npg_0FvTX1UGYZPQ

# MySQL driver
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.driver-class-name=org.postgresql.Driver



# ===============================
# JPA / HIBERNATE CONFIGURATION
# ===============================

# Automatically update database tables according to your entities
spring.jpa.hibernate.ddl-auto=update

# Show SQL queries in console
spring.jpa.show-sql=true

# Format SQL queries
spring.jpa.properties.hibernate.format_sql=true


# ===============================
# SERVER CONFIGURATION
# ===============================

server.port=9090